game:
- game/**

common:
- rootex/common/**

core:
- rootex/core/*

core-renderer:
- rootex/core/renderer/**

core-audio:
- rootex/core/audio/**

framework:
- rootex/framework/**

main:
- rootex/main/**

os:
- rootex/os/**

script:
- rootex/script/**

vendor:
- rootex/vendor/**
