game:
- game/**

editor:
- editor/**

app:
- rootex/app/**

common:
- rootex/common/**

core:
- rootex/core/**

framework:
- rootex/framework/**

main:
- rootex/main/**

os:
- rootex/os/**

script:
- rootex/script/**

vendor:
- rootex/vendor/**
