game:
- game/**

common:
- rootex/common/**

core:
- rootex/core/**

framework:
- rootex/framework/**

os:
- rootex/os/**

scene:
- rootex/scene/**

script:
- rootex/script/**

vendor:
- rootex/vendor/**

cmake:
- **/CMakeLists.txt
