name: clang-format-action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: '.'
        exclude: './rootex/vendor'
        extensions: 'h,cpp'
        clangFormatVersion: 9
