name: C/C++ CI

on: [push]

jobs:
  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016]
        type: ['Release', 'Debug']
    
    steps:
    - uses: actions/checkout@v1

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ matrix.os }}-${{ matrix.type }}

    - name: build with cmake
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        cmakeAppendedArgs: '-DCMAKE_BUILD_TYPE=${{ matrix.type }} -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache'
        buildWithCMake: true
        buildDirectory: '${{ github.workspace }}/build'
    
    - uses: actions/upload-artifact@v2
      with:
        name: Rootex-${{ github.run_id }}
        path: |
          build/editor/Debug/Editor.exe
          build/editor/Debug/*.dll

          build/game/Debug/Game.exe
          build/game/Debug/*.dll
          
          rootex.root
          imgui.ini
          build_fonts.bat

          editor/assets/
          editor/editor.app.json

          game/assets/
          game/game.app.json

          rootex/assets/
          rootex/vendor/**/LICENSE

          LICENSE
          README.md
