name: C/C++ CI

on: [push]

jobs:
  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016]
    
    steps:
    - uses: actions/checkout@v1

    - name: configure
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 15 2017" -A x64

    - name: cache
      uses: actions/cache@v2
      with:
        path: ./build/rootex/vendor/
        key: ${{ hashFiles('rootex/vendor/**', '.github/workflows/cpp.yml') }}

    - name: build
      run: ./build.bat

    - uses: actions/upload-artifact@v2
      with:
        name: Rootex-${{ github.run_id }}
        path: |
          build/editor/Debug/Editor.exe
          build/editor/Debug/*.dll

          build/game/Debug/Game.exe
          build/game/Debug/*.dll
          
          rootex.root
          imgui.ini
          build_fonts.bat

          editor/assets/
          editor/editor.app.json

          game/assets/
          game/game.app.json

          rootex/assets/
          rootex/vendor/**/LICENSE

          LICENSE
          README.md
