name: C/C++ CI

on: [push]

jobs:
  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016]
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./generate_cache.bat /17
    - name: build
      run: ./build.bat      
